apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "flare.fullname" . }}-server
  labels:
    app.kubernetes.io/component: server
    {{- include "flare.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.server.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/component: server
      {{- include "flare.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: server
        {{- include "flare.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.server.podSecurityContext | nindent 8 }}
      serviceAccountName: {{ include "flare.serviceAccountName" . }}
      containers:
        - args: [ ]
          env: [ ]
          image: "{{ .Values.server.image.repository }}:{{ .Values.server.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.server.image.pullPolicy }}
          name: server
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          resources:
          {{- toYaml .Values.server.resources | nindent 12 }}
          securityContext:
          {{- toYaml .Values.server.securityContext | nindent 12 }}
      {{- with .Values.server.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.server.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
