apiVersion: v1
kind: Service
metadata:
  name: {{ include "flare.fullname" . }}-server
  labels:
    app.kubernetes.io/component: server
    {{- include "flare.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: http
  selector:
    app.kubernetes.io/component: server
    {{- include "flare.selectorLabels" . | nindent 4 }}
