apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "flare.serviceAccountName" . }}
  labels:
    {{- include "flare.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  namespace: {{ .Release.Namespace }}
{{- with .Values.imagePullSecrets }}
imagePullSecrets:
  {{- toYaml . | nindent 2 }}
{{- end }}
