//go:build !ignore_autogenerated

// Copyright 2025 Clastix Labs
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Intent) DeepCopyInto(out *Intent) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Intent.
func (in *Intent) DeepCopy() *Intent {
	if in == nil {
		return nil
	}
	out := new(Intent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Intent) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntentConstraint) DeepCopyInto(out *IntentConstraint) {
	*out = *in
	in.Deadline.DeepCopyInto(&out.Deadline)
	if in.Providers != nil {
		in, out := &in.Providers, &out.Providers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.Availability.DeepCopyInto(&out.Availability)
	out.Negotiation = in.Negotiation
	out.Energy = in.Energy
	in.Compliance.DeepCopyInto(&out.Compliance)
	in.Performance.DeepCopyInto(&out.Performance)
	in.Security.DeepCopyInto(&out.Security)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntentConstraint.
func (in *IntentConstraint) DeepCopy() *IntentConstraint {
	if in == nil {
		return nil
	}
	out := new(IntentConstraint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntentConstraintAvailabilityMaintenanceWindow) DeepCopyInto(out *IntentConstraintAvailabilityMaintenanceWindow) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntentConstraintAvailabilityMaintenanceWindow.
func (in *IntentConstraintAvailabilityMaintenanceWindow) DeepCopy() *IntentConstraintAvailabilityMaintenanceWindow {
	if in == nil {
		return nil
	}
	out := new(IntentConstraintAvailabilityMaintenanceWindow)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntentList) DeepCopyInto(out *IntentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Intent, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntentList.
func (in *IntentList) DeepCopy() *IntentList {
	if in == nil {
		return nil
	}
	out := new(IntentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IntentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntentSLA) DeepCopyInto(out *IntentSLA) {
	*out = *in
	if in.MaxInterruptionTime != nil {
		in, out := &in.MaxInterruptionTime, &out.MaxInterruptionTime
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntentSLA.
func (in *IntentSLA) DeepCopy() *IntentSLA {
	if in == nil {
		return nil
	}
	out := new(IntentSLA)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntentSpec) DeepCopyInto(out *IntentSpec) {
	*out = *in
	in.Constraints.DeepCopyInto(&out.Constraints)
	in.SLA.DeepCopyInto(&out.SLA)
	in.Workload.DeepCopyInto(&out.Workload)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntentSpec.
func (in *IntentSpec) DeepCopy() *IntentSpec {
	if in == nil {
		return nil
	}
	out := new(IntentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntentStatus) DeepCopyInto(out *IntentStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntentStatus.
func (in *IntentStatus) DeepCopy() *IntentStatus {
	if in == nil {
		return nil
	}
	out := new(IntentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntentWorkload) DeepCopyInto(out *IntentWorkload) {
	*out = *in
	out.Batch = in.Batch
	if in.Commands != nil {
		in, out := &in.Commands, &out.Commands
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Secrets != nil {
		in, out := &in.Secrets, &out.Secrets
		*out = make([]IntentWorkloadSecret, len(*in))
		copy(*out, *in)
	}
	in.Storage.DeepCopyInto(&out.Storage)
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = make([]IntentWorkloadPort, len(*in))
		copy(*out, *in)
	}
	out.Scaling = in.Scaling
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntentWorkload.
func (in *IntentWorkload) DeepCopy() *IntentWorkload {
	if in == nil {
		return nil
	}
	out := new(IntentWorkload)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntentWorkloadBatch) DeepCopyInto(out *IntentWorkloadBatch) {
	*out = *in
	out.Timeout = in.Timeout
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntentWorkloadBatch.
func (in *IntentWorkloadBatch) DeepCopy() *IntentWorkloadBatch {
	if in == nil {
		return nil
	}
	out := new(IntentWorkloadBatch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntentWorkloadConstraintAvailability) DeepCopyInto(out *IntentWorkloadConstraintAvailability) {
	*out = *in
	if in.DaysOfWeek != nil {
		in, out := &in.DaysOfWeek, &out.DaysOfWeek
		*out = make([]DayOfWeek, len(*in))
		copy(*out, *in)
	}
	if in.BlackoutDates != nil {
		in, out := &in.BlackoutDates, &out.BlackoutDates
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.MaintenanceWindows != nil {
		in, out := &in.MaintenanceWindows, &out.MaintenanceWindows
		*out = make([]IntentConstraintAvailabilityMaintenanceWindow, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntentWorkloadConstraintAvailability.
func (in *IntentWorkloadConstraintAvailability) DeepCopy() *IntentWorkloadConstraintAvailability {
	if in == nil {
		return nil
	}
	out := new(IntentWorkloadConstraintAvailability)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntentWorkloadConstraintCompliance) DeepCopyInto(out *IntentWorkloadConstraintCompliance) {
	*out = *in
	if in.DataResidency != nil {
		in, out := &in.DataResidency, &out.DataResidency
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Certifications != nil {
		in, out := &in.Certifications, &out.Certifications
		*out = make([]Certification, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntentWorkloadConstraintCompliance.
func (in *IntentWorkloadConstraintCompliance) DeepCopy() *IntentWorkloadConstraintCompliance {
	if in == nil {
		return nil
	}
	out := new(IntentWorkloadConstraintCompliance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntentWorkloadConstraintEnergy) DeepCopyInto(out *IntentWorkloadConstraintEnergy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntentWorkloadConstraintEnergy.
func (in *IntentWorkloadConstraintEnergy) DeepCopy() *IntentWorkloadConstraintEnergy {
	if in == nil {
		return nil
	}
	out := new(IntentWorkloadConstraintEnergy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntentWorkloadConstraintNegotiation) DeepCopyInto(out *IntentWorkloadConstraintNegotiation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntentWorkloadConstraintNegotiation.
func (in *IntentWorkloadConstraintNegotiation) DeepCopy() *IntentWorkloadConstraintNegotiation {
	if in == nil {
		return nil
	}
	out := new(IntentWorkloadConstraintNegotiation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntentWorkloadConstraintPerformance) DeepCopyInto(out *IntentWorkloadConstraintPerformance) {
	*out = *in
	out.MinNetworkBandwidth = in.MinNetworkBandwidth.DeepCopy()
	out.MaxColdStartTime = in.MaxColdStartTime
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntentWorkloadConstraintPerformance.
func (in *IntentWorkloadConstraintPerformance) DeepCopy() *IntentWorkloadConstraintPerformance {
	if in == nil {
		return nil
	}
	out := new(IntentWorkloadConstraintPerformance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntentWorkloadConstraintSecurity) DeepCopyInto(out *IntentWorkloadConstraintSecurity) {
	*out = *in
	if in.FirewallRules != nil {
		in, out := &in.FirewallRules, &out.FirewallRules
		*out = make([]IntentWorkloadConstraintSecurityFirewallRule, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntentWorkloadConstraintSecurity.
func (in *IntentWorkloadConstraintSecurity) DeepCopy() *IntentWorkloadConstraintSecurity {
	if in == nil {
		return nil
	}
	out := new(IntentWorkloadConstraintSecurity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntentWorkloadConstraintSecurityFirewallRule) DeepCopyInto(out *IntentWorkloadConstraintSecurityFirewallRule) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntentWorkloadConstraintSecurityFirewallRule.
func (in *IntentWorkloadConstraintSecurityFirewallRule) DeepCopy() *IntentWorkloadConstraintSecurityFirewallRule {
	if in == nil {
		return nil
	}
	out := new(IntentWorkloadConstraintSecurityFirewallRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntentWorkloadPort) DeepCopyInto(out *IntentWorkloadPort) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntentWorkloadPort.
func (in *IntentWorkloadPort) DeepCopy() *IntentWorkloadPort {
	if in == nil {
		return nil
	}
	out := new(IntentWorkloadPort)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntentWorkloadResource) DeepCopyInto(out *IntentWorkloadResource) {
	*out = *in
	out.CPU = in.CPU.DeepCopy()
	out.Memory = in.Memory.DeepCopy()
	in.GPU.DeepCopyInto(&out.GPU)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntentWorkloadResource.
func (in *IntentWorkloadResource) DeepCopy() *IntentWorkloadResource {
	if in == nil {
		return nil
	}
	out := new(IntentWorkloadResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntentWorkloadResourceGPU) DeepCopyInto(out *IntentWorkloadResourceGPU) {
	*out = *in
	out.MemoryMin = in.MemoryMin.DeepCopy()
	out.MemoryMax = in.MemoryMax.DeepCopy()
	out.ClockSpeedMin = in.ClockSpeedMin.DeepCopy()
	if in.Shared != nil {
		in, out := &in.Shared, &out.Shared
		*out = new(bool)
		**out = **in
	}
	if in.Interruptible != nil {
		in, out := &in.Interruptible, &out.Interruptible
		*out = new(bool)
		**out = **in
	}
	if in.MultiInstance != nil {
		in, out := &in.MultiInstance, &out.MultiInstance
		*out = new(bool)
		**out = **in
	}
	if in.Dedicated != nil {
		in, out := &in.Dedicated, &out.Dedicated
		*out = new(bool)
		**out = **in
	}
	if in.Topology != nil {
		in, out := &in.Topology, &out.Topology
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntentWorkloadResourceGPU.
func (in *IntentWorkloadResourceGPU) DeepCopy() *IntentWorkloadResourceGPU {
	if in == nil {
		return nil
	}
	out := new(IntentWorkloadResourceGPU)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntentWorkloadScaling) DeepCopyInto(out *IntentWorkloadScaling) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntentWorkloadScaling.
func (in *IntentWorkloadScaling) DeepCopy() *IntentWorkloadScaling {
	if in == nil {
		return nil
	}
	out := new(IntentWorkloadScaling)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntentWorkloadSecret) DeepCopyInto(out *IntentWorkloadSecret) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntentWorkloadSecret.
func (in *IntentWorkloadSecret) DeepCopy() *IntentWorkloadSecret {
	if in == nil {
		return nil
	}
	out := new(IntentWorkloadSecret)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntentWorkloadStorage) DeepCopyInto(out *IntentWorkloadStorage) {
	*out = *in
	if in.Volumes != nil {
		in, out := &in.Volumes, &out.Volumes
		*out = make([]IntentWorkloadStorageVolume, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntentWorkloadStorage.
func (in *IntentWorkloadStorage) DeepCopy() *IntentWorkloadStorage {
	if in == nil {
		return nil
	}
	out := new(IntentWorkloadStorage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntentWorkloadStorageVolume) DeepCopyInto(out *IntentWorkloadStorageVolume) {
	*out = *in
	out.Size = in.Size.DeepCopy()
	out.Source = in.Source
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntentWorkloadStorageVolume.
func (in *IntentWorkloadStorageVolume) DeepCopy() *IntentWorkloadStorageVolume {
	if in == nil {
		return nil
	}
	out := new(IntentWorkloadStorageVolume)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntentWorkloadStorageVolumeSource) DeepCopyInto(out *IntentWorkloadStorageVolumeSource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntentWorkloadStorageVolumeSource.
func (in *IntentWorkloadStorageVolumeSource) DeepCopy() *IntentWorkloadStorageVolumeSource {
	if in == nil {
		return nil
	}
	out := new(IntentWorkloadStorageVolumeSource)
	in.DeepCopyInto(out)
	return out
}
